---
# tasks file for SSH
- name: Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    path: "{{ sshd_config }}"
    owner: root
    group: root
    mode: 0600

- name: Ensure SSH Protocol is set to 2
  lineinfile:
    path: "{{ sshd_config }}"
    line: Protocol 2 
    insertafter: EOF
    state: present  

- name: Ensure SSH LogLevel is set
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: '^(.*)#LogLevel INFO (.*)$'
    line: LogLevel INFO  

- name: Ensure SSH root login is disabled
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: '^(.*)#PermitRootLogin yes(.*)$'
    line: PermitRootLogin no

- name: Ensure SSH Idle Timeout Interval is configured
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: '^(.*)#ClientAliveInterval 0(.*)$'
    line: ClientAliveInterval 300

- name: Ensure SSH Idle Timeout Interval is configured
  lineinfile:
    path: "{{ sshd_config }}"
    regexp: '^(.*)#ClientAliveCountMax 3(.*)$'
    line: ClientAliveCountMax 0

- name: Ensure SSH access is limited
  lineinfile:
    path: "{{ sshd_config }}"
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_file:          
    - ssh_access
...

